Importing cowin_vaccine_data_districtwise.csv

In [1]:
import pandas as pd
dist_wise = pd.read_csv('cowin_vaccine_data_districtwise.csv', low_memory=False)

Import neighbor-districts-modified.json for getting the list of District Keys

In [2]:
import json
with open('neighbor-districts-modified.json') as json_file:
    data = json.load(json_file)
dist_keys = list(data.keys())

Getting List of all Column names of the cowin_vaccine_data_districtwise.csv and getting only the dates from them

In [3]:
lst = list(dist_wise)
lst
list1=lst[6:]
date_list = []
for i in range(len(list1)):
    if i%10 == 0:
        date_list.append(list1[i])

We only have to take data upto 14/08/2021. So, removing the later dates from the date list

In [4]:
date_list=date_list[:date_list.index('14/08/2021')+1]
date_list

['16/01/2021',
 '17/01/2021',
 '18/01/2021',
 '19/01/2021',
 '20/01/2021',
 '21/01/2021',
 '22/01/2021',
 '23/01/2021',
 '24/01/2021',
 '25/01/2021',
 '26/01/2021',
 '27/01/2021',
 '28/01/2021',
 '29/01/2021',
 '30/01/2021',
 '31/01/2021',
 '01/02/2021',
 '02/02/2021',
 '03/02/2021',
 '04/02/2021',
 '05/02/2021',
 '06/02/2021',
 '07/02/2021',
 '08/02/2021',
 '09/02/2021',
 '10/02/2021',
 '11/02/2021',
 '12/02/2021',
 '13/02/2021',
 '14/02/2021',
 '15/02/2021',
 '16/02/2021',
 '17/02/2021',
 '18/02/2021',
 '19/02/2021',
 '20/02/2021',
 '21/02/2021',
 '22/02/2021',
 '23/02/2021',
 '24/02/2021',
 '25/02/2021',
 '26/02/2021',
 '27/02/2021',
 '28/02/2021',
 '01/03/2021',
 '02/03/2021',
 '03/03/2021',
 '04/03/2021',
 '05/03/2021',
 '06/03/2021',
 '07/03/2021',
 '08/03/2021',
 '09/03/2021',
 '10/03/2021',
 '11/03/2021',
 '12/03/2021',
 '13/03/2021',
 '14/03/2021',
 '15/03/2021',
 '16/03/2021',
 '17/03/2021',
 '18/03/2021',
 '19/03/2021',
 '20/03/2021',
 '21/03/2021',
 '22/03/2021',
 '23/03/2021',
 '24/03/2021',
 '25/03/2021',
 '26/03/2021',
 '27/03/2021',
 '28/03/2021',
 '29/03/2021',
 '30/03/2021',
 '31/03/2021',
 '01/04/2021',
 '02/04/2021',
 '03/04/2021',
 '04/04/2021',
 '05/04/2021',
 '06/04/2021',
 '07/04/2021',
 '08/04/2021',
 '09/04/2021',
 '10/04/2021',
 '11/04/2021',
 '12/04/2021',
 '13/04/2021',
 '14/04/2021',
 '15/04/2021',
 '16/04/2021',
 '17/04/2021',
 '18/04/2021',
 '19/04/2021',
 '20/04/2021',
 '21/04/2021',
 '22/04/2021',
 '23/04/2021',
 '24/04/2021',
 '25/04/2021',
 '26/04/2021',
 '27/04/2021',
 '28/04/2021',
 '29/04/2021',
 '30/04/2021',
 '01/05/2021',
 '02/05/2021',
 '03/05/2021',
 '04/05/2021',
 '05/05/2021',
 '06/05/2021',
 '07/05/2021',
 '08/05/2021',
 '09/05/2021',
 '10/05/2021',
 '11/05/2021',
 '12/05/2021',
 '13/05/2021',
 '14/05/2021',
 '15/05/2021',
 '16/05/2021',
 '17/05/2021',
 '18/05/2021',
 '19/05/2021',
 '20/05/2021',
 '21/05/2021',
 '22/05/2021',
 '23/05/2021',
 '24/05/2021',
 '25/05/2021',
 '26/05/2021',
 '27/05/2021',
 '28/05/2021',
 '29/05/2021',
 '30/05/2021',
 '31/05/2021',
 '01/06/2021',
 '02/06/2021',
 '03/06/2021',
 '04/06/2021',
 '05/06/2021',
 '06/06/2021',
 '07/06/2021',
 '08/06/2021',
 '09/06/2021',
 '10/06/2021',
 '11/06/2021',
 '12/06/2021',
 '13/06/2021',
 '14/06/2021',
 '15/06/2021',
 '16/06/2021',
 '17/06/2021',
 '18/06/2021',
 '19/06/2021',
 '20/06/2021',
 '21/06/2021',
 '22/06/2021',
 '23/06/2021',
 '24/06/2021',
 '25/06/2021',
 '26/06/2021',
 '27/06/2021',
 '28/06/2021',
 '29/06/2021',
 '30/06/2021',
 '01/07/2021',
 '02/07/2021',
 '03/07/2021',
 '04/07/2021',
 '05/07/2021',
 '06/07/2021',
 '07/07/2021',
 '08/07/2021',
 '09/07/2021',
 '10/07/2021',
 '11/07/2021',
 '12/07/2021',
 '13/07/2021',
 '14/07/2021',
 '15/07/2021',
 '16/07/2021',
 '17/07/2021',
 '18/07/2021',
 '19/07/2021',
 '20/07/2021',
 '21/07/2021',
 '22/07/2021',
 '23/07/2021',
 '24/07/2021',
 '25/07/2021',
 '26/07/2021',
 '27/07/2021',
 '28/07/2021',
 '29/07/2021',
 '30/07/2021',
 '31/07/2021',
 '01/08/2021',
 '02/08/2021',
 '03/08/2021',
 '04/08/2021',
 '05/08/2021',
 '06/08/2021',
 '07/08/2021',
 '08/08/2021',
 '09/08/2021',
 '10/08/2021',
 '11/08/2021',
 '12/08/2021',
 '13/08/2021',
 '14/08/2021']

Replacing the NaN values with 0

In [5]:
for j in date_list:
    dist_wise[j+'.8']=dist_wise[j+'.8'].fillna(0)
    dist_wise[j+'.9']=dist_wise[j+'.9'].fillna(0)

Getting the number of covaxin vaccinated people and covishield vaccinated people.
Since, the data is cumulative we only consider the data from the last date .i.e. here 14/08/2021

In [6]:
cova_dist=[0]*len(dist_keys)
covi_dist=[0]*len(dist_keys)
for i in range(len(dist_keys)):
    k=list(dist_wise['District_Key']).index(dist_keys[i])
    cova_dist[i]=dist_wise[date_list[-1]+'.8'][k]
    covi_dist[i]=dist_wise[date_list[-1]+'.9'][k]

Taking the ratio of covishield vaccinated people to covaxin vaccinated people for all districts.
Where, Covaxin vaccinated people count is zero, we get dividingbyzero exception. So, implementing a try except block to catch dividingbyzero exception and setting the value that is greatest of all values of the ratio i.e. 9999999999 so that it becomes easy to sort the values according to the ratio

In [7]:
covi_cova_dist=[0]*len(dist_keys)
for i in range(len(dist_keys)):
    try:
        covi_cova_dist[i]=int(covi_dist[i])/int(cova_dist[i])
    except:
        covi_cova_dist[i]=9999999999

In [8]:
covi_cova_dist

[5.98511267861403,
 4.760976071323436,
 6.160042442833724,
 3.9683476973510285,
 4.2254540766824755,
 5.534183492738221,
 4.1990831637692025,
 5.34494289884293,
 6.978177317438603,
 4.740345182907292,
 6.649220064486288,
 4.747233750187003,
 7.5690274394420385,
 9999999999,
 9999999999,
 9999999999,
 9999999999,
 9999999999,
 9999999999,
 9999999999,
 9999999999,
 9999999999,
 9999999999,
 9999999999,
 9999999999,
 9999999999,
 9999999999,
 9999999999,
 9999999999,
 9999999999,
 9999999999,
 9999999999,
 9999999999,
 9999999999,
 9999999999,
 9999999999,
 9999999999,
 9999999999,
 11.674975239352921,
 0.8175445806790419,
 12.216243484109635,
 15.814410705095213,
 6.434405784686705,
 18.212495851310987,
 8.426559459182629,
 13.707793337392363,
 7.591344185094185,
 26.01483619763695,
 10.516255716842315,
 6.966074313408724,
 19.283851730589337,
 8.341581278081263,
 9.651270911931709,
 4.182027522682772,
 11.631636264633814,
 10.335952017645903,
 6.658854390889314,
 8.94332908434247,
 11.069834362717575,
 17.365908155465398,
 12.638580337785392,
 14.405619171290285,
 15.125707002310206,
 11.7251862429675,
 18.731442403177756,
 11.4971495792236,
 1.3939737445866878,
 12.509420856125727,
 25.941048764195056,
 28.86867780643714,
 14.125757838212367,
 6708.41,
 9999999999,
 33.226082099972075,
 5.469385185863395,
 9999999999,
 11.548283337653462,
 9999999999,
 13.51980242211444,
 6.499893591636948,
 4.536206031551369,
 4.720655190463493,
 9999999999,
 9999999999,
 33.087710403569254,
 9999999999,
 9999999999,
 9999999999,
 9999999999,
 9999999999,
 9999999999,
 6.726733617021277,
 446515.0,
 15.206162781732672,
 43.67124655319958,
 38.30916214172795,
 0.9303614262811958,
 4.937625959083108,
 30.478238154563357,
 9999999999,
 57.171148645200795,
 6.030363847515532,
 9999999999,
 9999999999,
 9999999999,
 11.319773027840261,
 23.977343713579785,
 17.161193853660457,
 9999999999,
 214.97393992932862,
 10.367930312164717,
 9.606410477339308,
 11.715129191268078,
 8.420972708482727,
 9.51517490506036,
 10.246417738730258,
 11.244778307072188,
 8.250141660895297,
 9.659682253401586,
 7.572022010690344,
 13.750803514034711,
 9.328887905697943,
 7.164629781141338,
 13.188924625926443,
 13.318946366232941,
 11.319749048206338,
 19.884892086330936,
 38.32673745173745,
 7.094414663669376,
 7.140739453749392,
 3.4352665696748477,
 4.573453138031693,
 31.314583333333335,
 10.480257192317204,
 11.937609502598367,
 9.100798879658806,
 3.129454809416095,
 6.491727775633604,
 1.785724561787149,
 3.328080229226361,
 4.2277111644018115,
 2.850941572185294,
 4.503272476748191,
 3.4407559154470144,
 2.209949336521148,
 4.995633249684545,
 2.7277479666046527,
 8321.659574468085,
 9999999999,
 9999999999,
 25.88249804228661,
 356.00897072710103,
 13.599348403185584,
 2.861830399438023,
 9.347207995003123,
 2.954907695769044,
 8.696972410378502,
 10.374626704176585,
 11.59723576052957,
 5.3114356081116485,
 2.650625841519972,
 10.956105487363036,
 160.0110294117647,
 4.044001333654398,
 12.152644251589322,
 3.3174342934974526,
 21.8693620709145,
 18.39083450070042,
 3.6876517143980254,
 10.57586524795452,
 10.140088016931502,
 7.052749426570711,
 9.073093757631545,
 4.486903030383902,
 3.3741068674497745,
 6.026456138711762,
 4.80080755775425,
 4.125337895637297,
 23.7693086735309,
 11.824899182256077,
 12.203733945969885,
 7.018887173514622,
 15.041494060049985,
 10.935487087446406,
 5.309292784778395,
 9999999999,
 253.40512147078135,
 9999999999,
 821.9781710914455,
 9999999999,
 9999999999,
 9999999999,
 9999999999,
 9999999999,
 9999999999,
 9999999999,
 5291.575757575758,
 4.505848806527316,
 6.2220096088985555,
 4.576433165843291,
 8.64733315387022,
 7.315406356113133,
 6.304393815527157,
 14.585696361355081,
 6.444446106664672,
 9.528461403376735,
 5.761180708814748,
 3.3610857597079518,
 7.4522796126610045,
 7.089421877166227,
 8.60392554269561,
 3.105898669356403,
 5.60534860967344,
 5.075654929033255,
 9.470062672131503,
 5.030808020170489,
 7.077680130452978,
 3.859330161726604,
 6.98307933503764,
 6.2685520335141165,
 14.157017114914426,
 5.692587388274833,
 4.740681197359436,
 4.442216179469749,
 4.638085554035124,
 10.37806211020382,
 6.247920651636614,
 6.009578995304722,
 5.373148581593484,
 3.135452955768527,
 5.142938592786553,
 3.069781291713728,
 6.341752891052952,
 7.67745493107105,
 3.9463053004382016,
 5.213446858485026,
 3.436266312193588,
 4.789187734436763,
 4.031428213468704,
 5.902631224462305,
 6.543840056059213,
 8.850540931936282,
 7.044558983921472,
 34.426419641512275,
 9999999999,
 27.700262692328312,
 9999999999,
 9999999999,
 6.963872431031291,
 9999999999,
 9999999999,
 9999999999,
 31.99225352112676,
 32022.6,
 9999999999,
 51.53589196872779,
 9999999999,
 9999999999,
 128.7941325240263,
 9999999999,
 6.997038512272716,
 9999999999,
 4.5828100625303145,
 5.626696533761616,
 11.659714925022561,
 7.683354231489652,
 7.7418412432115815,
 4.1247704027862815,
 6.808134714420842,
 7.0644665932665,
 7.950235034020906,
 6.367731576827283,
 7.494157149484194,
 9.973852274202878,
 6.921736354931376,
 5.083721053890942,
 7.9817076932568325,
 9.44386285432475,
 5.569367814938908,
 5.929802723706731,
 5.2800193478173245,
 8.523663066781543,
 7.921231522109078,
 4.344446930707839,
 6.564432055117396,
 10.520535216502509,
 12.113639363570826,
 5.898466562305375,
 11.530330142990824,
 7.535168948006537,
 7.365808875615575,
 9.363789327866902,
 7.803769541099345,
 10.248386468411143,
 7.3553821279209455,
 7.061523472099203,
 11.246067035695724,
 10.60468994036139,
 9.605252435254554,
 10.433406266655446,
 10.01953230779982,
 7.796840608950844,
 10.158254705206929,
 8.249604911602525,
 9999999999,
 9999999999,
 3.8884608449610254,
 4.345422711355678,
 3.3628811553468076,
 11.801827801827802,
 5.608603533417423,
 1.18200693259198,
 2.957847949462121,
 9.356230340488935,
 3.3995421508900536,
 3.9623322007463933,
 1.409047594475119,
 3.5977255175129095,
 6.4932881576892525,
 4.415916834105006,
 12.462183901000483,
 3.959435048796751,
 11.840653375675393,
 13.790508685899399,
 3.3332083741853626,
 5.788325239948777,
 7.8866733063507874,
 3.7096896541915174,
 10.883140066470256,
 2.8001883215208236,
 10.13006244221328,
 6.977175771326314,
 2.758072925483292,
 10.272647474637624,
 7.684562921808501,
 2.5243195041628774,
 17.643159916548,
 8.850747723585974,
 6.372762148337596,
 1.5209167038962768,
 4.619382138128931,
 9999999999,
 9999999999,
 9999999999,
 9999999999,
 9999999999,
 9999999999,
 9999999999,
 9999999999,
 9999999999,
 9999999999,
 9999999999,
 9999999999,
 9999999999,
 9999999999,
 9999999999,
 9999999999,
 9999999999,
 9999999999,
 9999999999,
 9999999999,
 9999999999,
 9999999999,
 9999999999,
 9999999999,
 9999999999,
 9999999999,
 9999999999,
 14.744149846936129,
 13.651417628597265,
 10.188655462184874,
 6.537578875837298,
 10.16683455049106,
 17.872895106912342,
 7.582410784752885,
 16.626320289709284,
 6.974469451655204,
 4.708253571923984,
 7.069161679922108,
 7.869182651832674,
 11.277455338766774,
 6.094385453535985,
 10.486231178794299,
 13.292393666563179,
 10.078423392398722,
 14.97136119555644,
 5.773240641937222,
 10.964894290798323,
 6.2538764694654345,
 5.078372604368941,
 2.784700280975798,
 12.356519079819225,
 11.708688776532954,
 9.356446421073912,
 12.1582912519815,
 11.260548285198556,
 13.805385412740295,
 10.522191906061169,
 12.954360069916488,
 11.698766834333929,
 20.7046028060967,
 4.647186245275665,
 6.943232578170383,
 9.144766895069193,
 15.381186464945355,
 4.340802447013327,
 15.317550914515502,
 7.455826204136636,
 10.418594717733324,
 18.29236394781921,
 11.357857769973661,
 8.564615189122792,
 10.942472040038304,
 14.481884949221632,
 22.23256044883571,
 3.8930761818821407,
 6.395420403918015,
 19.460147016431247,
 12.026330532212885,
 9999999999,
 9999999999,
 9999999999,
 9999999999,
 9999999999,
 9999999999,
 9999999999,
 9999999999,
 9999999999,
 9999999999,
 9999999999,
 9999999999,
 9999999999,
 9999999999,
 9999999999,
 9999999999,
 9999999999,
 9999999999,
 9999999999,
 9999999999,
 9999999999,
 9999999999,
 9999999999,
 9999999999,
 9999999999,
 9999999999,
 9999999999,
 9999999999,
 2.720724030069213,
 9999999999,
 9999999999,
 9999999999,
 9999999999,
 9999999999,
 9999999999,
 29965.739130434784,
 0.23133879598266568,
 645614.0,
 9999999999,
 9999999999,
 9999999999,
 9999999999,
 9999999999,
 9999999999,
 9999999999,
 9999999999,
 9999999999,
 8987.824742268042,
 7.563644408858172,
 5.994712809420812,
 4.572627473638596,
 7.020673318498313,
 3.5247451989092387,
 4.989029166362597,
 12.43063583815029,
 9.896941407689473,
 5.4591915438735334,
 8.207126781067762,
 9.182249101013403,
 5.1523378698635955,
 7.672957614305823,
 15.693399736676398,
 6.34707757273078,
 8.954459876122131,
 5.95463796875795,
 5.07239152267779,
 5.005437187835873,
 5.893627450980392,
 4.6189245565133925,
 12.80588491717524,
 9999999999,
 9999999999,
 9999999999,
 3.8965012917633666,
 7.698256337134238,
 10.819095735791327,
 19.37828458106098,
 9.541493470362976,
 25.768473993029513,
 14.06058881232364,
 4.556992048764302,
 8.230764870112385,
 15.521058175819372,
 21.33082769739735,
 10.286264142673206,
 10.476821565531242,
 17.57299160261495,
 7.346559226963615,
 5.624335389951949,
 3.2402498197018224,
 6.562567804389552,
 27.78664390181045,
 21.10195710769952,
 5.648891524262763,
 4.599335817139327,
 18.589096064845776,
 7.070679083949226,
 6.923008951396138,
 19.031794697098732,
 21.430332443581655,
 14.774137015400957,
 9.096768465909092,
 5.727120919555471,
 13.508163835352073,
 4.37857597165895,
 6.68755555337298,
 9999999999,
 9999999999,
 9999999999,
 9999999999,
 10.971296457860758,
 8.709575230014876,
 2.195341649599702,
 9.77500088248791,
 11.912725372354325,
 3.6733859563417584,
 12.876040466128826,
 14.772432054356514,
 5.76728894445179,
 6.388270230141054,
 8.135766423357664,
 7.6764181356746,
 7.414389022807343,
 11.004909841407777,
 9.248867584326488,
 3.49829277935521,
 15.011159631246967,
 36.848344671201815,
 10.673868312757202,
 11.360465692345802,
 21.063335570123368,
 11.173957204767063,
 12.405450733752621,
 2.0917717354681136,
 4.330860399891432,
 6.055321293574129,
 11.676631466990807,
 61.064331937571374,
 17.437205188679247,
 11.690930015104653,
 7.1229495330036885,
 3.6037524229826765,
 8.966186854970125,
 2.69187813138854,
 5.141286165167778,
 6.402927448323331,
 7.587946247732436,
 7.8468970299318155,
 5.595258526539146,
 9.834739229024944,
 8.464851697183853,
 8.044672887056526,
 6.1287967977395805,
 6.083021254806678,
 6.556728560862626,
 7.972892096461891,
 6.503158849883741,
 7.198540000993197,
 8.590828263921384,
 9.456327820107786,
 10.555059000753202,
 9.007245581293226,
 7.359357608522818,
 7.583364328398919,
 7.17608183563078,
 8.848023005032351,
 6.673536079736934,
 8.163099945723811,
 6.7939992154790785,
 6.690466342673973,
 6.920297670405522,
 6.906149997090824,
 2.9603262465827704,
 10.242697327532628,
 11.439185991481306,
 9999999999,
 10215.588235294117,
 9999999999,
 9999999999,
 745.8591304347826,
 9999999999,
 9999999999,
 13.357724815350643,
 8.11172899608576,
 4.662817468010857,
 11.106779977974941,
 3.052419554324242,
 5.79738224530752,
 11.123678792038435,
 8.101778575507874,
 5.689911554120455,
 14.903806188971446,
 10.822295488239329,
 5.2730879987672274,
 6.260716841931399,
 7.657892290818508,
 12.779726001026694,
 7.155922812982025,
 15.785476960741454,
 8.86054309222862,
 5.453224526085162,
 10.962770890508185,
 8.906525176862255,
 17.77402822676023,
 8.949900429724348,
 12.484447735928905,
 9.891355807689168,
 9.687060882610327,
 7.969925266402111,
 3.101741305556227,
 4.818378187953684,
 8.663837350208698,
 8.049877275792312,
 6.115053579783007,
 6.6183169487517315,
 7.606483241736084,
 10.59163454493326,
 10.922404281143109,
 12.000787847793335,
 5.091265434989097,
 17.12863178179662,
 5.94490180580045,
 5.582792993322365,
 18.502543654612953,
 19.054922141874805,
 10.180953954875621,
 8.65909024340236,
 12.43996779881929,
 4.029314571366772,
 9.31661550648579,
 9.556604695080258,
 5.290416114438461,
 4.444676048054386,
 11.77328346828365,
 10.808172313755541,
 6.418749837421637,
 7.958389467760364,
 5.673505011945799,
 7.181288804122874,
 6.016446784594451,
 16.317737106228652,
 7.229334115576416,
 6.378055286393972,
 10.649150639461096,
 13.449281508831454,
 6.750403668539689,
 12.227317732297406,
 4.997184738031753,
 11.756195322575023,
 15.223663068323262,
 5.0250835333427455,
 8.168781011816462,
 11.009014239886197,
 7.940467817454736,
 3.048922753039565,
 8.438349785807413,
 8.309889566721731,
 5.421807873144648,
 7.388389851699398,
 22.083988212180746,
 19.61589655828104,
 19.803892354967875,
 8.684191064801976,
 11.549311566578464,
 12.369868444764823,
 25.996259351620946,
 9.936346616742444,
 20.736530060328686,
 26.485639335440908,
 15.854561894363314,
 24.77230153678276,
 5.801152840503922,
 5.243532958950645,
 6.028829284612685,
 6.618885502453365,
 6.204536644533643,
 6.092694438885707,
 8.159629774981148,
 7.63254141078026,
 6.731340116244798,
 6.655950914431915,
 6.485293577644769,
 5.267038992862527,
 4.759492031344751,
 5.354458527059344,
 6.774300655310863,
 6.334672008401563,
 7.181486469556502,
 9.289012819023275,
 9.334140974059173,
 6.27572724310644,
 5.601778001425756,
 6.350596514745308,
 5.1886283856988085]

Combining columns to a dataframe

In [9]:
data_final = {'districtid':dist_keys, 'vaccineratio':covi_cova_dist}
data_dist = pd.DataFrame(data_final)
data_dist

               districtid  vaccineratio
0            AP_Anantapur      5.985113
1             AP_Chittoor      4.760976
2        AP_East Godavari      6.160042
3               AP_Guntur      3.968348
4              AP_Krishna      4.225454
..                    ...           ...
708    WB_Purba Bardhaman      9.334141
709    WB_Purba Medinipur      6.275727
710            WB_Purulia      5.601778
711  WB_South 24 Parganas      6.350597
712     WB_Uttar Dinajpur      5.188628

[713 rows x 2 columns]

Sorting the dataframe with respect to the vaccineratio column

In [10]:
data_dist=data_dist.sort_values('vaccineratio')

Replacing 9999999999 with 'N/A'

In [11]:
for i in range(len(data_dist)):
    if data_dist['vaccineratio'][i]==9999999999:
        data_dist['vaccineratio'][i]= 'N/A'

C:\Users\manda\AppData\Roaming\Python\Python37\site-packages\ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until
C:\Users\manda\AppData\Local\Programs\Python\Python37\lib\site-packages\pandas\core\indexing.py:1732: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_single_block(indexer, value, name)

In [12]:
data_dist

         districtid vaccineratio
455      OR_Khordha     0.231339
39       AS_Barpeta     0.817545
96         BR_Patna     0.930361
311     MH_Bhandara     1.182007
66      AS_Sonitpur     1.393974
..              ...          ...
438        OR_Angul          N/A
439     OR_Balangir          N/A
440      OR_Bargarh          N/A
34   AR_Upper Siang          N/A
356  MN_Imphal West          N/A

[713 rows x 2 columns]

Exporting the modified dataframe to district-vaccine-type-ratio.csv

In [13]:
data_dist.to_csv('district-vaccine-type-ratio.csv',index=False)

Getting the state code list for all states from district keys and taking the unique codes from them and sorting them

In [14]:
states = [i.split('_')[0] for i in dist_keys]
states = set(states)
states = list(states)
states.sort()
states

['AP',
 'AR',
 'AS',
 'BR',
 'CH',
 'CT',
 'DL',
 'DN',
 'GA',
 'GJ',
 'HP',
 'HR',
 'JH',
 'JK',
 'KA',
 'KL',
 'LA',
 'MH',
 'ML',
 'MN',
 'MP',
 'MZ',
 'NL',
 'OR',
 'PB',
 'PY',
 'RJ',
 'SK',
 'TG',
 'TN',
 'TR',
 'UP',
 'UT',
 'WB']

Getting the list of state names from the state codes in the previous list using the state codes and state names from cowin_vaccine_data_districtwise.csv file

In [15]:
state_keys = [0]*len(states)
for i in range(len(states)):
    k=list(dist_wise['State_Code']).index(states[i])
    state_keys[i]=dist_wise['State'][k]
state_keys

['Andhra Pradesh',
 'Arunachal Pradesh',
 'Assam',
 'Bihar',
 'Chandigarh',
 'Chhattisgarh',
 'Delhi',
 'Dadra and Nagar Haveli and Daman and Diu',
 'Goa',
 'Gujarat',
 'Himachal Pradesh',
 'Haryana',
 'Jharkhand',
 'Jammu and Kashmir',
 'Karnataka',
 'Kerala',
 'Ladakh',
 'Maharashtra',
 'Meghalaya',
 'Manipur',
 'Madhya Pradesh',
 'Mizoram',
 'Nagaland',
 'Odisha',
 'Punjab',
 'Puducherry',
 'Rajasthan',
 'Sikkim',
 'Telangana',
 'Tamil Nadu',
 'Tripura',
 'Uttar Pradesh',
 'Uttarakhand',
 'West Bengal']

Getting the number of covaxin vaccinated people and covishield vaccinated people.
We find that data for each state by adding the data for all districts which are a part of that state

In [16]:
cova_state=[0]*len(states)
covi_state=[0]*len(states)
for i in range(len(states)):
    tmpca=0
    tmpci=0
    l=[ind for ind,el in enumerate(dist_keys) if el.split('_')[0] == states[i]]
    for j in l:
        tmpca=tmpca+int(cova_dist[j])
        tmpci=tmpci+int(covi_dist[j])
    cova_state[i]=tmpca
    covi_state[i]=tmpci

Taking the ratio of covishield vaccinated people to covaxin vaccinated people for all states.
Where, Covaxin vaccinated people count is zero, we get dividingbyzero exception. So, implementing a try except block to catch dividingbyzero exception and setting the value that is greatest of all values of the ratio i.e. 9999999999 so that it becomes easy to sort the values according to the ratio

In [17]:
covi_cova_state=[0]*len(states)
for i in range(len(states)):
    try:
        covi_cova_state[i]=int(covi_state[i])/int(cova_state[i])
    except:
        covi_cova_state[i]=9999999999

In [18]:
covi_cova_state

[5.129828417390091,
 9999999999,
 7.006831531602256,
 7.8442210522377795,
 214.97393992932862,
 7.679274460037256,
 3.2224026619649226,
 14654.340425531915,
 51.16299081640032,
 7.018432869129609,
 1947.0027132951461,
 5.953967985179986,
 5.095742336948367,
 24.762025141647136,
 7.255612208258528,
 9.027857491328223,
 9999999999,
 6.579185817982559,
 9999999999,
 9999999999,
 7.758749864247849,
 9999999999,
 9999999999,
 6.229572471861442,
 6.4452668644020985,
 9999999999,
 7.457664481281255,
 9999999999,
 4.23385669152066,
 5.317590871889261,
 48.197015420828684,
 7.4635881769032775,
 12.731979218387655,
 6.292723713944701]

Combining the columns into a dataframe

In [19]:
data_final = {'stateid':state_keys, 'vaccineratio':covi_cova_state}
data_state = pd.DataFrame(data_final)
data_state

                                     stateid  vaccineratio
0                             Andhra Pradesh  5.129828e+00
1                          Arunachal Pradesh  1.000000e+10
2                                      Assam  7.006832e+00
3                                      Bihar  7.844221e+00
4                                 Chandigarh  2.149739e+02
5                               Chhattisgarh  7.679274e+00
6                                      Delhi  3.222403e+00
7   Dadra and Nagar Haveli and Daman and Diu  1.465434e+04
8                                        Goa  5.116299e+01
9                                    Gujarat  7.018433e+00
10                          Himachal Pradesh  1.947003e+03
11                                   Haryana  5.953968e+00
12                                 Jharkhand  5.095742e+00
13                         Jammu and Kashmir  2.476203e+01
14                                 Karnataka  7.255612e+00
15                                    Kerala  9.027857e+00
16                                    Ladakh  1.000000e+10
17                               Maharashtra  6.579186e+00
18                                 Meghalaya  1.000000e+10
19                                   Manipur  1.000000e+10
20                            Madhya Pradesh  7.758750e+00
21                                   Mizoram  1.000000e+10
22                                  Nagaland  1.000000e+10
23                                    Odisha  6.229572e+00
24                                    Punjab  6.445267e+00
25                                Puducherry  1.000000e+10
26                                 Rajasthan  7.457664e+00
27                                    Sikkim  1.000000e+10
28                                 Telangana  4.233857e+00
29                                Tamil Nadu  5.317591e+00
30                                   Tripura  4.819702e+01
31                             Uttar Pradesh  7.463588e+00
32                               Uttarakhand  1.273198e+01
33                               West Bengal  6.292724e+00

Sorting the dataframe with respect to the vaccineratio column

In [20]:
data_state=data_state.sort_values('vaccineratio')

Replacing 9999999999 with 'N/A'

In [21]:
for i in range(len(data_state)):
    if data_state['vaccineratio'][i]==9999999999:
        data_state['vaccineratio'][i]= 'N/A'

C:\Users\manda\AppData\Roaming\Python\Python37\site-packages\ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until
C:\Users\manda\AppData\Local\Programs\Python\Python37\lib\site-packages\pandas\core\indexing.py:1732: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_single_block(indexer, value, name)

In [22]:
data_state

                                     stateid  vaccineratio
6                                      Delhi      3.222403
28                                 Telangana      4.233857
12                                 Jharkhand      5.095742
0                             Andhra Pradesh      5.129828
29                                Tamil Nadu      5.317591
11                                   Haryana      5.953968
23                                    Odisha      6.229572
33                               West Bengal      6.292724
24                                    Punjab      6.445267
17                               Maharashtra      6.579186
2                                      Assam      7.006832
9                                    Gujarat      7.018433
14                                 Karnataka      7.255612
26                                 Rajasthan      7.457664
31                             Uttar Pradesh      7.463588
5                               Chhattisgarh      7.679274
20                            Madhya Pradesh       7.75875
3                                      Bihar      7.844221
15                                    Kerala      9.027857
32                               Uttarakhand     12.731979
13                         Jammu and Kashmir     24.762025
30                                   Tripura     48.197015
8                                        Goa     51.162991
4                                 Chandigarh     214.97394
10                          Himachal Pradesh   1947.002713
7   Dadra and Nagar Haveli and Daman and Diu  14654.340426
21                                   Mizoram           N/A
25                                Puducherry           N/A
19                                   Manipur           N/A
27                                    Sikkim           N/A
18                                 Meghalaya           N/A
1                          Arunachal Pradesh           N/A
22                                  Nagaland           N/A
16                                    Ladakh           N/A

Exporting the modified dataframe to state-vaccine-type-ratio.csv

In [23]:
data_state.to_csv('state-vaccine-type-ratio.csv',index=False)

Getting the number of covaxin vaccinated people and the covishield vaccinated people overall. We find that by adding the respective data from all states

In [24]:
cova_overall=0
covi_overall=0
for i in range(len(states)):
    covi_overall=covi_overall+covi_state[i]
    cova_overall=cova_overall+cova_state[i]

Taking the ratio of covishield vaccinated people to covaxin vaccinated people overall

In [25]:
covi_cova_overall=int(covi_overall)/int(cova_overall)

In [26]:
covi_cova_overall

6.99358337053257

Combining the columns into a dataframe

In [27]:
data_final = {'Overall':['Overall'], 'vaccineratio':[covi_cova_overall]}
data_overall = pd.DataFrame(data_final)
data_overall

   Overall  vaccineratio
0  Overall      6.993583

Exporting dataframe to overall-vaccine-type-ratio.csv

In [28]:
data_overall.to_csv('overall-vaccine-type-ratio.csv',index=False)